<?php

$students = [
    [
        "firstName" => "James",
        "lastName" => "Fields",
        "grades" => [12, 11, 15],
        "average" => -1
    ],
    [
        "firstName" => "Richard",
        "lastName" => "Stein",
        "grades" => [18, 12, 13],
        "average" => -1
    ],
    [
        "firstName" => "Mark",
        "lastName" => "Hartoff",
        "grades" => [9, 11, 10],
        "average" => -1
    ],
    [
        "firstName" => "Thomas",
        "lastName" => "Nestle",
        "grades" => [9, 8, 5],
        "average" => -1
    ],
    [
        "firstName" => "Jeremy",
        "lastName" => "Brent",
        "grades" => [18, 15, 16],
        "average" => -1
    ]
];

?>

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Mini projet bulletin de notes</title>
    </head>
    <body>
        <?php
            foreach($students as $student)
            {
        ?>
        <article class="">
            <header>
                <h1>
                    <?= "$student[lastName] $student[firstName]"; ?>
                </h1>
            </header>
            <section>
                <h2>Notes : </h2>
                <ul>
                    <li>
                        <?php 
                            $i=0;
                            while($i < count($students['grades']))
                            {
                                echo $students[$i]['grades'][$i];
                                $i++;
                            }
                        ?>
                    </li>
                </ul>
            </section>
            <footer>
                <h3>Moyenne des notes de l'étudiant </h3>
            </footer>
        </article>
        <?php
            };
        ?>
    </body>
</html>