<?php

$students = [
    [
        "firstName" => "James",
        "lastName" => "Fields",
        "grades" => [12, 11, 15],
        "average" => -1
    ],
    [
        "firstName" => "Richard",
        "lastName" => "Stein",
        "grades" => [18, 12, 13],
        "average" => -1
    ],
    [
        "firstName" => "Mark",
        "lastName" => "Hartoff",
        "grades" => [9, 11, 10],
        "average" => -1
    ],
    [
        "firstName" => "Thomas",
        "lastName" => "Nestle",
        "grades" => [9, 8, 5],
        "average" => -1
    ],
    [
        "firstName" => "Jeremy",
        "lastName" => "Brent",
        "grades" => [18, 15, 16],
        "average" => -1
    ]
];

$average=0;

function average(float $grade1, float $grade2, float $grade3) : float
{
    $sum = $grade1 + $grade2 + $grade3;
    $average = $sum / 3;
    return $average;
}

?>

<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Mini projet bulletin de notes</title>
        <link rel="stylesheet" href="style.css" type="text/css" />
    </head>
    <body>
        <?php
            foreach($students as $student)
            {
                $student['average'] = average($student['grades'][0], $student['grades'][1], $student['grades'][2]);
        ?>
        <article class=
            <?php 
                if($student['average'] < 10)
                {
                    echo "red";
                }
                else if($student['average'] > 13)
                {
                    echo "green";
                }
                else 
                {
                    echo "orange";
                }
            ?>>    
            <header>
                <h1>
                    <?= "$student[lastName] $student[firstName]"; ?>
                </h1>
            </header>
            <section>
                <h2>Notes : </h2>
                <ul>
                    <?php
                        foreach($student['grades'] as $grade)
                        {
                    ?>
                    
                    <li><?= $grade ;?></li>
                    <?php
                        }
                    ?>
                </ul>
            </section>
            <footer>
                <h3><?= $student['average']; ?></h3>
            </footer>
        </article>
        <?php
            }
        ?>
    </body>
</html>